
- name: Preparation
  apt: name={{ item }} state=latest
  with_items:
    - git
    - build-essential
    - libssl-dev
    - autoconf
    - bison
    - libffi-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libgdbm3
    - libgdbm-dev
    - libsqlite3-dev


#############
### rbenv
#############

- name: Install rbenv
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/rbenv/rbenv.git dest=~/.rbenv

- name: Install ruby-build as rbenv plugin
  become: yes
  become_user: "{{ rbenv_user }}"
  git: repo=https://github.com/rbenv/ruby-build.git dest=~/.rbenv/plugins/ruby-build

- name: Add ~.rbenv/bin to PATH
  become: yes
  become_user: "{{ rbenv_user }}"
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: Eval rbenv init in ~/.profile
  become: yes
  become_user: "{{ rbenv_user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'

# TODO: maybe need to do "source ~/.profile" here?


############
### ruby
############

- name: Check if version is installed ruby
  shell: "sudo -iu {{ rbenv_user }} rbenv versions | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_install
  changed_when: False
  ignore_errors: yes

- name: Install ruby (from original URL, not CDN)
  command: "sudo -iu {{ rbenv_user }} RUBY_BUILD_SKIP_MIRROR=1 rbenv install {{ rbenv_ruby_version }}"
  when: rbenv_check_install|failed

- name: Check if version is the default ruby version
  shell: "sudo -iu {{ rbenv_user }} rbenv version | grep {{ rbenv_ruby_version }}"
  register: rbenv_check_default
  changed_when: False
  ignore_errors: yes

- name: Set default ruby version
  command: "sudo -iu {{ rbenv_user }} rbenv global {{ rbenv_ruby_version }}"
  when: rbenv_check_default|failed


#######################
### bundler and rails
#######################

- name: Install rails and bundler
  become_user: "{{ rbenv_user }}"
  gem: name={{ item }} executable=.rbenv/shims/gem user_install=False include_doc=no
  with_items:
    - bundler
    - rails
